biConjugateGradientStabilized – CommonModules
biConjugateGradientStabilized Function
46 statements
Source File
public function biConjugateGradientStabilized(A, b, x0, tol, maxIts) result(x)
Arguments
Type Intent Optional Attributes Name
class(sparse_t), intent(in) :: A
real(kind=wp), intent(in), dimension(:) :: b
real(kind=wp), intent(in), optional dimension(:) :: x0
real(kind=wp), intent(in), optional :: tol
integer, intent(in), optional :: maxIts
Return Value real(kind=wp), dimension(:),allocatable
Calls
Called By
Source Code
biConjugateGradientStabilized
Source Code
    function biConjugateGradientStabilized(A,b,x0,tol,maxIts) result(x)
        class(sparse_t),intent(in)::A
        real(wp),dimension(:),intent(in)::b
        real(wp),dimension(:),intent(in),optional::x0
        real(wp),intent(in),optional::tol
        integer,intent(in),optional::maxIts
        real(wp),dimension(:),allocatable::x
        real(wp),dimension(:),allocatable::D,r,Ap,p,r0,s,As
        real(wp)::orho,rho,alpha,beta,omega
        integer::lmaxIts
        real(wp)::ltol
        real(wp)::rss0,rss
        integer::k
        lmaxIts = 1000000
        ltol    = 1.0E-6_wp
        if(present(maxIts)) lmaxIts = maxIts
        if(present(tol   )) ltol    = tol
        D = A%getDiagonal()
        x = b/D
        if(present(x0)) x = x0
        r = b-matmul(A,x)
        r0 = r
        rho   = 1.0_wp
        alpha = 1.0_wp
        omega = 1.0_wp
        Ap = [(0.0_wp,k=1,size(b))]
        p  = [(0.0_wp,k=1,size(b))]
        rss0 = sqrt(sum(r**2))
        call startReport('Bi-Conjugate Gradient (Stab) Solver')
        do k=1,lmaxIts
            orho = rho
            rho = sum(r0*r)
            beta = (rho/orho)*(alpha/omega)
            p = r+beta*(p-omega*Ap)
            Ap = matmul(A,p)
            alpha = rho/sum(r0*Ap)
            s = r-alpha*Ap
            As = matmul(A,s)
            omega = sum(As*s)/sum(As*As)
            x = x+alpha*p+omega*s
            r = s-omega*As
            rss = sqrt(sum(r**2))
            call solverProgress(k,rss/rss0,ltol,'Bi-Conjugate Gradient (Stab) Solver')
            if(rss/rss0<ltol) exit
        end do
    end function biConjugateGradientStabilized
All Procedures
abs_t acos_t add_t arg arrayToChar asin_t assignment(=) atan_t bar barh biCGSTAB_t biConjugateGradientStabilized binData box charToArray checkPrecision colorbar colorbar2 colorize colorMap config_t conjg conjugateGradient conjugateGradient_t contour contourf cos cos_t cpuTime cubicSpline_t deDup der DFT diff1 diff3 div_t doBar doContour doError doFillBetween doFunction doHist doLegend doLogPlot doPlot doQuiver doScatter doSurface endsWith errorbar eval_test eval_testN evalR_abs evalR_acos evalR_add evalR_asin evalR_atan evalR_cos evalR_div evalR_exp evalR_imag evalR_log evalR_log10 evalR_mul evalR_neg evalR_p evalR_pow evalR_real evalR_sin evalR_sqrt evalR_sub evalR_tan evalR_var evalZ_abs evalZ_acos evalZ_add evalZ_asin evalZ_atan evalZ_cos evalZ_div evalZ_exp evalZ_imag evalZ_log evalZ_log10 evalZ_mul evalZ_neg evalZ_p evalZ_pow evalZ_real evalZ_sin evalZ_sqrt evalZ_sub evalZ_tan evalZ_var exp exp exp_t f FFT FFT_freq figure fillBetween fillBetweenx findInterval flatten function_t gaussSeidel gaussSeidel_t get_adN hist iDFT iFFT imag_t intToChar inv jacobi jacobi_t labels legend linearInterp linearSpline_t lineSearch_t linspace log log log10 log10_t log_t makeLogo matmul matmul maxval mean meshGridX meshGridY minimumResidual minval mixval mul_t neg_t newAbs newAcos newAdd newAsin newAtan newCos newDiv newExp newImag newIterator newLog newLog10 newMul newNeg newNodeStack newPow newReal newSin newSparse newSpvec newSqrt newSub newTan newToken newVar nodeStack_t norm2 operator(*) operator(*) operator(*) operator(**) operator(+) operator(+) operator(+) operator(-) operator(-) operator(.d.) operator(.o.) operator(.o.) operator(.oo.) operator(.sx.) operator(.x.) operator(/) operator(/) plot plot3 pop pow_t printTypes push quat_t quiver randomNormal randomUniform readGrid readStep real real_t realToChar realToTime removeSpaces scaler scatter set_adN setRandomSeed setup show showProgress sin sin_t solveLU solverProgress SOR_t span sqrt sqrt_t startReport startsWith stDev steepestDescent sub_t subplot successiveOverRelaxation sum sum surface symmetricGaussSeidel symmetricSuccessiveOverRelaxation tan_t TDMA testBasic testBasicSolvers testColorize testColorMap testConstants testCpuTime testDeDup testDiff testDot testEndsWith testFFT testFlatten testFunction testIFFT testIntToChar testLinearInterp testLinspace testLU testMean testMeshGrid testMixval testNewConfig testNewSparse testNewSpline testNext testObjective testObjectiveN testPlot testPrecision testRandomNormal testRandomUniform testRead testReadGmsh testRealToChar testRealToTime testRemoveSpaces testSetRandomSeed testSolvers testSpan testSplineX testSpvec testStartsWith testStDev testTDMA testWallTime testWrite testWriteMat testWriteVTK testWriteVTK ticks title token_t tokenize toRPN transpose v2m var_t vector wait wallTime wireframe writeGrid writeGridVTK writeHeaderVTK writeMat writeScalarVTK writeStep writeVectorVTK xlabel xlim xticks xylim xyzlim ylabel ylim yticks
Call graph
biconjugategradientstabilized calls solverprogress, startreport
solverprogress calls showprogress
startreport calls showprogress
showprogress calls realtotime, colorize, realtochar, colormap, walltime
realtotime calls inttochar
colorize calls inttochar
testbasicsolvers calls biconjugategradientstabilized
testsparse_prg calls testbasicsolvers