doError – CommonModules
doError Subroutine
30 statements
Source File
subroutine doError()
Arguments
None
Calls
Called By
Source Code
doError
Source Code
    subroutine doError
        !! ![error](|media|/example-10.svg)
        integer,parameter::N = 25
        real(wp),dimension(N)::x,y,xe,ye
        real(wp),dimension(12)::r
        real(wp)::m,s
        integer::k
        x = linspace(0.0_wp,5.0_wp,N)
        y = 1.0_wp/(x**2+1.0_wp)
        do k=1,N
            call random_number(r)
            r = 0.25_wp*(2.0_wp*r-1.0_wp)
            m = sum(r)/real(size(r))
            s = sqrt(sum((r-m)**2)/real(size(r)-1))
            x(k) = x(k)+m
            xe(k) = s
            call random_number(r)
            r = 0.15_wp*(2.0_wp*r-1.0_wp)
            m = sum(r)/real(size(r))
            s = sqrt(sum((r-m)**2)/real(size(r)-1))
            y(k) = y(k)+m
            ye(k) = s
        end do
        call figure()
        call subplot(1,1,1)
        call xylim(mixval([x-xe,x+xe])+[-0.5_wp,0.5_wp],mixval([y-ye,y+ye])+[-0.2_wp,0.2_wp])
        call errorbar(x,y,xerr=xe,yerr=ye,lineColor='b',lineWidth=1.0_wp)
        call plot(x,y,lineStyle='',markStyle='s',markColor='r',markSize=1.5_wp)
        call ticks()
        call labels('x','y','')
    end subroutine doError
All Procedures
abs_t acos_t add_t arg arrayToChar asin_t assignment(=) atan_t bar barh biCGSTAB_t biConjugateGradientStabilized binData box charToArray checkPrecision colorbar colorbar2 colorize colorMap config_t conjg conjugateGradient conjugateGradient_t contour contourf cos cos_t cpuTime cubicSpline_t deDup der DFT diff1 diff3 div_t doBar doContour doError doFillBetween doFunction doHist doLegend doLogPlot doPlot doQuiver doScatter doSurface endsWith errorbar eval_test eval_testN evalR_abs evalR_acos evalR_add evalR_asin evalR_atan evalR_cos evalR_div evalR_exp evalR_imag evalR_log evalR_log10 evalR_mul evalR_neg evalR_p evalR_pow evalR_real evalR_sin evalR_sqrt evalR_sub evalR_tan evalR_var evalZ_abs evalZ_acos evalZ_add evalZ_asin evalZ_atan evalZ_cos evalZ_div evalZ_exp evalZ_imag evalZ_log evalZ_log10 evalZ_mul evalZ_neg evalZ_p evalZ_pow evalZ_real evalZ_sin evalZ_sqrt evalZ_sub evalZ_tan evalZ_var exp exp exp_t f FFT FFT_freq figure fillBetween fillBetweenx findInterval flatten function_t gaussSeidel gaussSeidel_t get_adN hist iDFT iFFT imag_t intToChar inv jacobi jacobi_t labels legend linearInterp linearSpline_t lineSearch_t linspace log log log10 log10_t log_t makeLogo matmul matmul maxval mean meshGridX meshGridY minimumResidual minval mixval mul_t neg_t newAbs newAcos newAdd newAsin newAtan newCos newDiv newExp newImag newIterator newLog newLog10 newMul newNeg newNodeStack newPow newReal newSin newSparse newSpvec newSqrt newSub newTan newToken newVar nodeStack_t norm2 operator(*) operator(*) operator(*) operator(**) operator(+) operator(+) operator(+) operator(-) operator(-) operator(.d.) operator(.o.) operator(.o.) operator(.oo.) operator(.sx.) operator(.x.) operator(/) operator(/) plot plot3 pop pow_t printTypes push quat_t quiver randomNormal randomUniform readGrid readStep real real_t realToChar realToTime removeSpaces scaler scatter set_adN setRandomSeed setup show showProgress sin sin_t solveLU solverProgress SOR_t span sqrt sqrt_t startReport startsWith stDev steepestDescent sub_t subplot successiveOverRelaxation sum sum surface symmetricGaussSeidel symmetricSuccessiveOverRelaxation tan_t TDMA testBasic testBasicSolvers testColorize testColorMap testConstants testCpuTime testDeDup testDiff testDot testEndsWith testFFT testFlatten testFunction testIFFT testIntToChar testLinearInterp testLinspace testLU testMean testMeshGrid testMixval testNewConfig testNewSparse testNewSpline testNext testObjective testObjectiveN testPlot testPrecision testRandomNormal testRandomUniform testRead testReadGmsh testRealToChar testRealToTime testRemoveSpaces testSetRandomSeed testSolvers testSpan testSplineX testSpvec testStartsWith testStDev testTDMA testWallTime testWrite testWriteMat testWriteVTK testWriteVTK ticks title token_t tokenize toRPN transpose v2m var_t vector wait wallTime wireframe writeGrid writeGridVTK writeHeaderVTK writeMat writeScalarVTK writeStep writeVectorVTK xlabel xlim xticks xylim xyzlim ylabel ylim yticks
Call graph
doerror calls mixval, figure, errorbar, subplot, labels, plot, linspace, ticks, xylim
figure calls pleop, pladv, plbop, plssub
errorbar calls plerry, plerrx
subplot calls pladv, plssub, plvasp, plvsta, plvpor
labels calls pllab
plot calls plptex, plline, plssym
ticks calls plbox
xylim calls plwind
examples_prg calls doerror