intToChar – CommonModules
intToChar Function
23 statements
Source File
public elemental function intToChar(a, f, l) result(o)
Create a string from an integer
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: a
Integer value to convert
character(len=*), intent(in), optional :: f
Format to use
integer, intent(in), optional :: l
Final length of string
Return Value character(len=:), allocatable
Called By
Source Code
intToChar
Source Code
    elemental function intToChar(a,f,l) result(o)
        !! Create a string from an integer
        integer,intent(in)::a
            !! Integer value to convert
        character(*),optional,intent(in)::f
            !! Format to use
        integer,optional,intent(in)::l
            !! Final length of string
        character(:),allocatable::o
        character(128)::buf
        if(present(l)) then
            allocate(character(l)::o)
            if(present(f)) then
                write(o,'('//f//')') a
            else
                write(o,*) a
            end if
            o = adjustl(o)
        else
            if(present(f)) then
                write(buf,'('//f//')') a
            else
                write(buf,*) a
            end if
            o = trim(adjustl(buf))
        end if
    end function intToChar
All Procedures
abs abs_t acos_t ad_t add_t arg arrayToChar asin_t assignment(=) atan_t bar barh biCGSTAB_t biConjugateGradientStabilized binData box charToArray checkPrecision colorbar colorbar2 colorize colorMap config_t conjg conjugateGradient conjugateGradient_t contour contourf cos_a cos_t cpuTime cubicSpline_t deDup DFT div_t doBar doContour doError doFillBetween doFunction doHist doLegend doLogPlot doPlot doQuiver doScatter doSurface endsWith errorbar eval_test eval_testN evalR_abs evalR_acos evalR_add evalR_asin evalR_atan evalR_cos evalR_div evalR_exp evalR_imag evalR_log evalR_log10 evalR_mul evalR_neg evalR_p evalR_pow evalR_real evalR_sin evalR_sqrt evalR_sub evalR_tan evalR_var evalZ_abs evalZ_acos evalZ_add evalZ_asin evalZ_atan evalZ_cos evalZ_div evalZ_exp evalZ_imag evalZ_log evalZ_log10 evalZ_mul evalZ_neg evalZ_p evalZ_pow evalZ_real evalZ_sin evalZ_sqrt evalZ_sub evalZ_tan evalZ_var exp exp exp_t f FFT FFT_freq figure fillBetween fillBetweenx findInterval flatten function_t gaussSeidel gaussSeidel_t hist iDFT iFFT imag_t intToChar inv jacobi jacobi_t labels legend linearInterp linearSpline_t lineSearch_t linspace log log log10 log10 log10_t log_t makeLogo matmul matmul maxval mean meshGridX meshGridY minimumResidual minval mixval mul_t neg_t newAbs newAcos newAdd newAsin newAtan newCos newDiv newExp newImag newIterator newLog newLog10 newMul newNeg newNodeStack newPow newReal newSin newSparse newSpvec newSqrt newSub newTan newToken newVar nint nodeStack_t norm2 norm2 operator(*) operator(*) operator(*) operator(**) operator(+) operator(+) operator(+) operator(-) operator(-) operator(.d.) operator(.o.) operator(.o.) operator(.oo.) operator(.sx.) operator(.x.) operator(/) operator(/) operator(<) operator(>) plot plot3 pop pow_t printTypes push quat_t quiver randomNormal randomUniform readGrid readStep real_t realToChar realToTime removeSpaces scaler scatter setRandomSeed setup show showProgress sin_a sin_t solveLU solveLU solverProgress SOR_t span sqrt sqrt_t startReport startsWith stDev steepestDescent sub_t subplot successiveOverRelaxation sum sum surface symmetricGaussSeidel symmetricSuccessiveOverRelaxation tan_a tan_t TDMA TDMA testBasic testBasicSolvers testColorize testColorMap testConstants testCpuTime testDeDup testDiff testDot testEndsWith testFFT testFlatten testFunction testIFFT testIntToChar testLinearInterp testLinspace testLU testMean testMeshGrid testMixval testNewConfig testNewSparse testNewSpline testNext testObjective testObjectiveN testPlot testPrecision testRandomNormal testRandomUniform testRead testReadGmsh testRealToChar testRealToTime testRemoveSpaces testSetRandomSeed testSolvers testSpan testSplineX testSpvec testStartsWith testStDev testTDMA testWallTime testWrite testWriteMat testWriteVTK testWriteVTK ticks title token_t tokenize toRPN transpose v2m var_t vector wait wallTime wireframe writeGrid writeGridVTK writeHeaderVTK writeMat writeScalarVTK writeStep writeVectorVTK xlabel xlim xticks xylim xyzlim ylabel ylim yticks
Call graph
realtotime calls inttochar
testinttochar calls inttochar
colorize calls inttochar
showprogress calls realtotime, colorize
testrealtotime calls realtotime
startreport calls showprogress
testnext calls showprogress
solverprogress calls showprogress
conjugategradient calls startreport, solverprogress
steepestdescent calls startreport, solverprogress
jacobi calls startreport, solverprogress
successiveoverrelaxation calls startreport, solverprogress
biconjugategradientstabilized calls startreport, solverprogress
symmetricsuccessiveoverrelaxation calls startreport, solverprogress
gaussseidel calls startreport, solverprogress
minimumresidual calls startreport, solverprogress
symmetricgaussseidel calls startreport, solverprogress
testbasicsolvers calls conjugategradient, successiveoverrelaxation, biconjugategradientstabilized
testsparse_prg calls testbasicsolvers
testiterate_prg calls testnext
testtext_prg calls testinttochar, testrealtotime, testcolorize
testcolorize calls colorize