linspace – CommonModules
linspace Function
14 statements
Source File
public function linspace(l, h, N) result(o)
Return an array of evenly-spaced values
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: l
Low-bound for values
real(kind=wp), intent(in) :: h
High-bound for values
integer, intent(in), optional :: N
Number of values (default 20)
Return Value real(kind=wp), dimension(:),allocatable
Called By
Source Code
linspace
Source Code
    function linspace(l,h,N) result(o)
        !! Return an array of evenly-spaced values
        real(wp),intent(in)::l
            !! Low-bound for values
        real(wp),intent(in)::h
            !! High-bound for values
        integer,intent(in),optional::N
            !! Number of values (default 20)
        real(wp),dimension(:),allocatable::o
        integer::Nl,i
        Nl = 20
        if(present(N)) Nl = N
        if(Nl==1) then
            o = [ (l+h)/2.0_wp ]
        else
            o = [( (h-l)*real(i-1,wp)/real(Nl-1,wp)+l , i=1 , Nl )]
        end if
    end function linspace
All Procedures
abs abs_t acos_t ad_t add_t arg arrayToChar asin_t assignment(=) atan_t bar barh biCGSTAB_t biConjugateGradientStabilized binData box charToArray checkPrecision colorbar colorbar2 colorize colorMap config_t conjg conjugateGradient conjugateGradient_t contour contourf cos_a cos_t cpuTime cubicSpline_t deDup DFT div_t doBar doContour doError doFillBetween doFunction doHist doLegend doLogPlot doPlot doQuiver doScatter doSurface endsWith errorbar eval_test eval_testN evalR_abs evalR_acos evalR_add evalR_asin evalR_atan evalR_cos evalR_div evalR_exp evalR_imag evalR_log evalR_log10 evalR_mul evalR_neg evalR_p evalR_pow evalR_real evalR_sin evalR_sqrt evalR_sub evalR_tan evalR_var evalZ_abs evalZ_acos evalZ_add evalZ_asin evalZ_atan evalZ_cos evalZ_div evalZ_exp evalZ_imag evalZ_log evalZ_log10 evalZ_mul evalZ_neg evalZ_p evalZ_pow evalZ_real evalZ_sin evalZ_sqrt evalZ_sub evalZ_tan evalZ_var exp exp exp_t f FFT FFT_freq figure fillBetween fillBetweenx findInterval flatten function_t gaussSeidel gaussSeidel_t hist iDFT iFFT imag_t intToChar inv jacobi jacobi_t labels legend linearInterp linearSpline_t lineSearch_t linspace log log log10 log10 log10_t log_t makeLogo matmul matmul maxval mean meshGridX meshGridY minimumResidual minval mixval mul_t neg_t newAbs newAcos newAdd newAsin newAtan newCos newDiv newExp newImag newIterator newLog newLog10 newMul newNeg newNodeStack newPow newReal newSin newSparse newSpvec newSqrt newSub newTan newToken newVar nint nodeStack_t norm2 norm2 operator(*) operator(*) operator(*) operator(**) operator(+) operator(+) operator(+) operator(-) operator(-) operator(.d.) operator(.o.) operator(.o.) operator(.oo.) operator(.sx.) operator(.x.) operator(/) operator(/) operator(<) operator(>) plot plot3 pop pow_t printTypes push quat_t quiver randomNormal randomUniform readGrid readStep real_t realToChar realToTime removeSpaces scaler scatter setRandomSeed setup show showProgress sin_a sin_t solveLU solveLU solverProgress SOR_t span sqrt sqrt_t startReport startsWith stDev steepestDescent sub_t subplot successiveOverRelaxation sum sum surface symmetricGaussSeidel symmetricSuccessiveOverRelaxation tan_a tan_t TDMA TDMA testBasic testBasicSolvers testColorize testColorMap testConstants testCpuTime testDeDup testDiff testDot testEndsWith testFFT testFlatten testFunction testIFFT testIntToChar testLinearInterp testLinspace testLU testMean testMeshGrid testMixval testNewConfig testNewSparse testNewSpline testNext testObjective testObjectiveN testPlot testPrecision testRandomNormal testRandomUniform testRead testReadGmsh testRealToChar testRealToTime testRemoveSpaces testSetRandomSeed testSolvers testSpan testSplineX testSpvec testStartsWith testStDev testTDMA testWallTime testWrite testWriteMat testWriteVTK testWriteVTK ticks title token_t tokenize toRPN transpose v2m var_t vector wait wallTime wireframe writeGrid writeGridVTK writeHeaderVTK writeMat writeScalarVTK writeStep writeVectorVTK xlabel xlim xticks xylim xyzlim ylabel ylim yticks
Call graph
testwritevtk calls linspace
basic_prg calls linspace
testwrite calls linspace
dosurface calls linspace, surface
doerror calls linspace
bindata calls linspace
docontour calls linspace, contourf
testlinspace calls linspace
surface calls linspace
dolegend calls linspace
testlinearinterp calls linspace
testmeshgrid calls linspace
testtdma calls linspace
contourf calls linspace
dologplot calls linspace
doquiver calls linspace
dobar calls linspace
testbasicsolvers calls linspace
makelogo calls linspace
dofillbetween calls linspace
testsolvers calls linspace
doplot calls linspace
dofunction calls linspace
animate_prg calls linspace
testvtkio_prg calls testwritevtk
testnetcdf_prg calls testwrite
examples_prg calls dosurface, doerror, docontour, dolegend, dologplot, doquiver, dobar, dofillbetween, doplot, dohist
dohist calls bindata, hist
hist calls bindata
testarray_prg calls testlinspace, testlinearinterp, testmeshgrid, testtdma
testsparse_prg calls testbasicsolvers, testsolvers
logo_prg calls makelogo
testfunction calls dofunction
testeval_prg calls testfunction