plot – CommonModules
plot Subroutine
35 statements
Source File
public subroutine plot(x, y, lineColor, lineStyle, lineWidth, markColor, markStyle, markSize)
Plot data using lines and or markers
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: x
x-data for plot
real(kind=wp), intent(in), dimension(:) :: y
y-data for plot
character(len=*), intent(in), optional :: lineColor
Color of line
character(len=*), intent(in), optional :: lineStyle
Style of line; '' for no line
real(kind=wp), intent(in), optional :: lineWidth
Width of line
character(len=*), intent(in), optional :: markColor
Color of markers, if any
character(len=*), intent(in), optional :: markStyle
Style of markers; '' or absent for none
real(kind=wp), intent(in), optional :: markSize
Size of markers, if any
Calls
Called By
Source Code
plot
Source Code
    subroutine plot(x,y,lineColor,lineStyle,lineWidth,markColor,markStyle,markSize)
        !! Plot data using lines and or markers
        real(wp),dimension(:),intent(in)::x
            !! x-data for plot
        real(wp),dimension(:),intent(in)::y
            !! y-data for plot
        character(*),intent(in),optional::lineColor
            !! Color of line
        character(*),intent(in),optional::lineStyle
            !! Style of line; '' for no line
        real(wp),intent(in),optional::lineWidth
            !! Width of line
        character(*),intent(in),optional::markColor
            !! Color of markers, if any
        character(*),intent(in),optional::markStyle
            !! Style of markers; '' or absent for none
        real(wp),intent(in),optional::markSize
            !! Size of markers, if any
        real(pp),dimension(:),allocatable::xl,yl
        character(32)::code
        integer::k
        xl = localize(x)
        yl = localize(y)
        if(present(lineColor)) call setColor(lineColor)
        if(present(lineWidth)) call setLineWidth(lineWidth)
        if(present(lineStyle)) then
            call setLineStyle(lineStyle)
            if(lineStyle/='') call plline(xl,yl)
        else
            call plline(xl,yl)
        end if
        call resetPen()
        if(present(markColor)) call setColor(markColor)
        if(present(markSize)) call plssym(0.0_pp,real(markSize,pp))
        if(present(markStyle)) then
            code = getSymbolCode(markStyle)
            if(markStyle/='') then
                do k=1,size(x)
                    call plptex(xl(k),yl(k),0.0_pp,0.0_pp,0.5_pp,code)
                end do
            end if
        end if
        call resetPen()
    end subroutine plot
All Procedures
abs_t acos_t add_t arg arrayToChar asin_t assignment(=) atan_t bar barh biCGSTAB_t biConjugateGradientStabilized binData box charToArray checkPrecision colorbar colorbar2 colorize colorMap config_t conjg conjugateGradient conjugateGradient_t contour contourf cos cos_t cpuTime cubicSpline_t deDup der DFT diff1 diff3 div_t doBar doContour doError doFillBetween doFunction doHist doLegend doLogPlot doPlot doQuiver doScatter doSurface endsWith errorbar eval_test eval_testN evalR_abs evalR_acos evalR_add evalR_asin evalR_atan evalR_cos evalR_div evalR_exp evalR_imag evalR_log evalR_log10 evalR_mul evalR_neg evalR_p evalR_pow evalR_real evalR_sin evalR_sqrt evalR_sub evalR_tan evalR_var evalZ_abs evalZ_acos evalZ_add evalZ_asin evalZ_atan evalZ_cos evalZ_div evalZ_exp evalZ_imag evalZ_log evalZ_log10 evalZ_mul evalZ_neg evalZ_p evalZ_pow evalZ_real evalZ_sin evalZ_sqrt evalZ_sub evalZ_tan evalZ_var exp exp exp_t f FFT FFT_freq figure fillBetween fillBetweenx findInterval flatten function_t gaussSeidel gaussSeidel_t get_adN hist iDFT iFFT imag_t intToChar inv jacobi jacobi_t labels legend linearInterp linearSpline_t lineSearch_t linspace log log log10 log10_t log_t makeLogo matmul matmul maxval mean meshGridX meshGridY minimumResidual minval mixval mul_t neg_t newAbs newAcos newAdd newAsin newAtan newCos newDiv newExp newImag newIterator newLog newLog10 newMul newNeg newNodeStack newPow newReal newSin newSparse newSpvec newSqrt newSub newTan newToken newVar nodeStack_t norm2 operator(*) operator(*) operator(*) operator(**) operator(+) operator(+) operator(+) operator(-) operator(-) operator(.d.) operator(.o.) operator(.o.) operator(.oo.) operator(.sx.) operator(.x.) operator(/) operator(/) plot plot3 pop pow_t printTypes push quat_t quiver randomNormal randomUniform readGrid readStep real real_t realToChar realToTime removeSpaces scaler scatter set_adN setRandomSeed setup show showProgress sin sin_t solveLU solverProgress SOR_t span sqrt sqrt_t startReport startsWith stDev steepestDescent sub_t subplot successiveOverRelaxation sum sum surface symmetricGaussSeidel symmetricSuccessiveOverRelaxation tan_t TDMA testBasic testBasicSolvers testColorize testColorMap testConstants testCpuTime testDeDup testDiff testDot testEndsWith testFFT testFlatten testFunction testIFFT testIntToChar testLinearInterp testLinspace testLU testMean testMeshGrid testMixval testNewConfig testNewSparse testNewSpline testNext testObjective testObjectiveN testPlot testPrecision testRandomNormal testRandomUniform testRead testReadGmsh testRealToChar testRealToTime testRemoveSpaces testSetRandomSeed testSolvers testSpan testSplineX testSpvec testStartsWith testStDev testTDMA testWallTime testWrite testWriteMat testWriteVTK testWriteVTK ticks title token_t tokenize toRPN transpose v2m var_t vector wait wallTime wireframe writeGrid writeGridVTK writeHeaderVTK writeMat writeScalarVTK writeStep writeVectorVTK xlabel xlim xticks xylim xyzlim ylabel ylim yticks
Call graph
plot calls plptex, plline, plssym
dofillbetween calls plot
makelogo calls plot
testsplinex calls plot
animate_prg calls plot
testsolvers calls plot
dolegend calls plot
basic_prg calls plot
doerror calls plot
testbasicsolvers calls plot
dologplot calls plot
doplot calls plot
dofunction calls plot
examples_prg calls dofillbetween, dolegend, doerror, dologplot, doplot
logo_prg calls makelogo
testspline_prg calls testsplinex
testsparse_prg calls testsolvers, testbasicsolvers
testfunction calls dofunction
testeval_prg calls testfunction