showProgress – CommonModules
showProgress Subroutine
35 statements
Source File
public subroutine showProgress(m, p, ml)
Create a progress bar through successive calls
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: m
Message to display
real(kind=wp), intent(in) :: p
Progress fraction \(p\in[0,1]\)
0 = start progress
1 = complete progress
integer, intent(in), optional :: ml
Message reserve length (used to align long messages)
Calls
Called By
Source Code
showProgress
Source Code
    subroutine showProgress(m,p,ml)
        !! Create a progress bar through successive calls
        character(*),intent(in)::m
            !! Message to display
        real(wp),intent(in)::p
            !! Progress fraction \(p\in[0,1]\)
            !! 0 = start progress
            !! 1 = complete progress
        integer,intent(in),optional::ml
            !! Message reserve length (used to align long messages)
        real(wp)::r
        real(wp),save::po
        real(wp),save::tStart
        real(wp)::tNow
        integer::mld
        integer::N,k
        N = 40
        mld = 40
        if(present(ml)) mld = ml
        if(p<=0.0_wp) then
            po = p
            tStart = wallTime()
        else if(p-po<=0.005 .and. p<1.0_wp) then
            return
        else
            po = p
        end if
        tNow = wallTime()
        write(stdout,'(1A)',advance='no') achar(13)//colorize(m//repeat(' ',mld-len(m))//' [',[5,5,0])
        do k=1,N
            r = real(k-1,wp)/real(N-1,wp)
            if(r<=p) then
                write(stdout,'(1A)',advance='no') colorize('=',colorMap(r,[0.0_wp,1.0_wp]))
            else
                write(stdout,'(1A)',advance='no') colorize(' ',[0,0,0])
            end if
        end do
        write(stdout,'(1A,1A,1X,1A,1A,1A,1A,1A,1A)',advance='no') colorize('] ',[5,5,0]), &
        & colorize(realToChar(100.0_wp*p,'1F5.1'),colorMap(p,[0.0_wp,1.0_wp])), &
        & colorize('%',[5,5,0]), colorize(' (',[5,5,0]), realToTime(tNow-tStart), &
        & colorize(' / ',[5,5,0]), realToTime( (tNow-tStart)/(p+0.0001_wp) ), colorize(')',[5,5,0])
        if(p>=1.0_wp) write(stdout,'(1A)') repeat(' ',10)
        flush(stdout)
    end subroutine showProgress
All Procedures
abs abs_t acos_t ad_t add_t arg arrayToChar asin_t assignment(=) atan_t bar barh biCGSTAB_t biConjugateGradientStabilized binData box charToArray checkPrecision colorbar colorbar2 colorize colorMap config_t conjg conjugateGradient conjugateGradient_t contour contourf cos_a cos_t cpuTime cubicSpline_t deDup DFT div_t doBar doContour doError doFillBetween doFunction doHist doLegend doLogPlot doPlot doQuiver doScatter doSurface endsWith errorbar eval_test eval_testN evalR_abs evalR_acos evalR_add evalR_asin evalR_atan evalR_cos evalR_div evalR_exp evalR_imag evalR_log evalR_log10 evalR_mul evalR_neg evalR_p evalR_pow evalR_real evalR_sin evalR_sqrt evalR_sub evalR_tan evalR_var evalZ_abs evalZ_acos evalZ_add evalZ_asin evalZ_atan evalZ_cos evalZ_div evalZ_exp evalZ_imag evalZ_log evalZ_log10 evalZ_mul evalZ_neg evalZ_p evalZ_pow evalZ_real evalZ_sin evalZ_sqrt evalZ_sub evalZ_tan evalZ_var exp exp exp_t f FFT FFT_freq figure fillBetween fillBetweenx findInterval flatten function_t gaussSeidel gaussSeidel_t hist iDFT iFFT imag_t intToChar inv jacobi jacobi_t labels legend linearInterp linearSpline_t lineSearch_t linspace log log log10 log10 log10_t log_t makeLogo matmul matmul maxval mean meshGridX meshGridY minimumResidual minval mixval mul_t neg_t newAbs newAcos newAdd newAsin newAtan newCos newDiv newExp newImag newIterator newLog newLog10 newMul newNeg newNodeStack newPow newReal newSin newSparse newSpvec newSqrt newSub newTan newToken newVar nint nodeStack_t norm2 norm2 operator(*) operator(*) operator(*) operator(**) operator(+) operator(+) operator(+) operator(-) operator(-) operator(.d.) operator(.o.) operator(.o.) operator(.oo.) operator(.sx.) operator(.x.) operator(/) operator(/) operator(<) operator(>) plot plot3 pop pow_t printTypes push quat_t quiver randomNormal randomUniform readGrid readStep real_t realToChar realToTime removeSpaces scaler scatter setRandomSeed setup show showProgress sin_a sin_t solveLU solveLU solverProgress SOR_t span sqrt sqrt_t startReport startsWith stDev steepestDescent sub_t subplot successiveOverRelaxation sum sum surface symmetricGaussSeidel symmetricSuccessiveOverRelaxation tan_a tan_t TDMA TDMA testBasic testBasicSolvers testColorize testColorMap testConstants testCpuTime testDeDup testDiff testDot testEndsWith testFFT testFlatten testFunction testIFFT testIntToChar testLinearInterp testLinspace testLU testMean testMeshGrid testMixval testNewConfig testNewSparse testNewSpline testNext testObjective testObjectiveN testPlot testPrecision testRandomNormal testRandomUniform testRead testReadGmsh testRealToChar testRealToTime testRemoveSpaces testSetRandomSeed testSolvers testSpan testSplineX testSpvec testStartsWith testStDev testTDMA testWallTime testWrite testWriteMat testWriteVTK testWriteVTK ticks title token_t tokenize toRPN transpose v2m var_t vector wait wallTime wireframe writeGrid writeGridVTK writeHeaderVTK writeMat writeScalarVTK writeStep writeVectorVTK xlabel xlim xticks xylim xyzlim ylabel ylim yticks
Call graph
showprogress calls walltime, realtochar, colormap, realtotime, colorize
realtotime calls inttochar
colorize calls inttochar
startreport calls showprogress
testnext calls showprogress
solverprogress calls showprogress
conjugategradient calls startreport, solverprogress
steepestdescent calls startreport, solverprogress
jacobi calls startreport, solverprogress
successiveoverrelaxation calls startreport, solverprogress
biconjugategradientstabilized calls startreport, solverprogress
symmetricsuccessiveoverrelaxation calls startreport, solverprogress
gaussseidel calls startreport, solverprogress
minimumresidual calls startreport, solverprogress
symmetricgaussseidel calls startreport, solverprogress
testbasicsolvers calls conjugategradient, successiveoverrelaxation, biconjugategradientstabilized
testsparse_prg calls testbasicsolvers
testiterate_prg calls testnext