testFunction – CommonModules
testFunction Subroutine
20 statements
Source File
subroutine testFunction()
Verify operation of newFunction and eval
Arguments
None
Calls
Called By
Source Code
testFunction
Source Code
    subroutine testFunction
        !! Verify operation of newFunction and eval
        call setup(fileName='testsExpression-%n.svg',figSize=[400,300])
!         call doFunction('f(x) = x+1j',[-2.0_wp,2.0_wp])
        call doFunction('f(x) = x+1',[-2.0_wp,2.0_wp])
        call doFunction('f(x) = x-1',[-2.0_wp,2.0_wp])
        call doFunction('f(x) = 2*x',[-2.0_wp,2.0_wp])
        call doFunction('f(x) = x/2',[-2.0_wp,2.0_wp])
        call doFunction('f(x) = x^2',[-2.0_wp,2.0_wp])
        call doFunction('f(x) = sqrt(x^2)',[-2.0_wp,2.0_wp])
        call doFunction('f(x) = abs(x)',[-2.0_wp,2.0_wp])
        call doFunction('f(x) = exp(x)',[0.0_wp,1.0_wp])
        call doFunction('f(x) = log(exp(x))',[0.0_wp,1.0_wp])
        call doFunction('f(x) = sin(x)',[0.0_wp,2.0_wp*PI])
        call doFunction('f(x) = asin(sin(x))',[0.0_wp,2.0_wp*PI])
        call doFunction('f(x) = cos(x)',[0.0_wp,2.0_wp*PI])
        call doFunction('f(x) = acos(cos(x))',[0.0_wp,2.0_wp*PI])
        call doFunction('f(x) = 2*(x+1)/3',[0.0_wp,2.0_wp*PI])
        call doFunction('f(x) = (x+1)*(x-1)/6',[0.0_wp,2.0_wp*PI])
        call doFunction('f(x) = 4*(x+1)/(x^2+1)',[0.0_wp,2.0_wp*PI])
        call show()
    end subroutine testFunction
All Procedures
abs_t acos_t add_t arg arrayToChar asin_t assignment(=) atan_t bar barh biCGSTAB_t biConjugateGradientStabilized binData box charToArray checkPrecision colorbar colorbar2 colorize colorMap config_t conjg conjugateGradient conjugateGradient_t contour contourf cos cos_t cpuTime cubicSpline_t deDup der DFT diff1 diff3 div_t doBar doContour doError doFillBetween doFunction doHist doLegend doLogPlot doPlot doQuiver doScatter doSurface endsWith errorbar eval_test eval_testN evalR_abs evalR_acos evalR_add evalR_asin evalR_atan evalR_cos evalR_div evalR_exp evalR_imag evalR_log evalR_log10 evalR_mul evalR_neg evalR_p evalR_pow evalR_real evalR_sin evalR_sqrt evalR_sub evalR_tan evalR_var evalZ_abs evalZ_acos evalZ_add evalZ_asin evalZ_atan evalZ_cos evalZ_div evalZ_exp evalZ_imag evalZ_log evalZ_log10 evalZ_mul evalZ_neg evalZ_p evalZ_pow evalZ_real evalZ_sin evalZ_sqrt evalZ_sub evalZ_tan evalZ_var exp exp exp_t f FFT FFT_freq figure fillBetween fillBetweenx findInterval flatten function_t gaussSeidel gaussSeidel_t get_adN hist iDFT iFFT imag_t intToChar inv jacobi jacobi_t labels legend linearInterp linearSpline_t lineSearch_t linspace log log log10 log10_t log_t makeLogo matmul matmul maxval mean meshGridX meshGridY minimumResidual minval mixval mul_t neg_t newAbs newAcos newAdd newAsin newAtan newCos newDiv newExp newImag newIterator newLog newLog10 newMul newNeg newNodeStack newPow newReal newSin newSparse newSpvec newSqrt newSub newTan newToken newVar nodeStack_t norm2 operator(*) operator(*) operator(*) operator(**) operator(+) operator(+) operator(+) operator(-) operator(-) operator(.d.) operator(.o.) operator(.o.) operator(.oo.) operator(.sx.) operator(.x.) operator(/) operator(/) plot plot3 pop pow_t printTypes push quat_t quiver randomNormal randomUniform readGrid readStep real real_t realToChar realToTime removeSpaces scaler scatter set_adN setRandomSeed setup show showProgress sin sin_t solveLU solverProgress SOR_t span sqrt sqrt_t startReport startsWith stDev steepestDescent sub_t subplot successiveOverRelaxation sum sum surface symmetricGaussSeidel symmetricSuccessiveOverRelaxation tan_t TDMA testBasic testBasicSolvers testColorize testColorMap testConstants testCpuTime testDeDup testDiff testDot testEndsWith testFFT testFlatten testFunction testIFFT testIntToChar testLinearInterp testLinspace testLU testMean testMeshGrid testMixval testNewConfig testNewSparse testNewSpline testNext testObjective testObjectiveN testPlot testPrecision testRandomNormal testRandomUniform testRead testReadGmsh testRealToChar testRealToTime testRemoveSpaces testSetRandomSeed testSolvers testSpan testSplineX testSpvec testStartsWith testStDev testTDMA testWallTime testWrite testWriteMat testWriteVTK testWriteVTK ticks title token_t tokenize toRPN transpose v2m var_t vector wait wallTime wireframe writeGrid writeGridVTK writeHeaderVTK writeMat writeScalarVTK writeStep writeVectorVTK xlabel xlim xticks xylim xyzlim ylabel ylim yticks
Call graph
testfunction calls setup, show, dofunction
setup calls plsetopt, plinit, plsdev, plsfam, plsfnam, plfontld
show calls plend
dofunction calls mixval, figure, subplot, span, labels, plot, linspace, ticks, xylim
figure calls pleop, pladv, plbop, plssub
subplot calls pladv, plssub, plvasp, plvsta, plvpor
labels calls pllab
plot calls plptex, plline, plssym
ticks calls plbox
xylim calls plwind
testeval_prg calls testfunction