testBasicSolvers – CommonModules
testBasicSolvers Subroutine
61 statements
Source File
subroutine testBasicSolvers()
Arguments
None
Calls
Called By
Source Code
testBasicSolvers
Source Code
    subroutine testBasicSolvers
        real(wp),parameter::Tl  = 0.0_wp
        real(wp),parameter::Tr  = 1.0_wp
        real(wp),parameter::k   = 1.0_wp
        real(wp),parameter::q0  = 10.0_wp
        real(wp),parameter::tol = 1.0E-8_wp
        real(wp)::Ap,Ae,Aw,dx
        type(sparse_t)::A
        real(wp),dimension(:),allocatable::x,q
        real(wp),dimension(:),allocatable::T1,T2,T3
        integer::N,i,s
        N  = 1000
        s  = N/30
        allocate(x(0:N+1))
        x  = linspace(0.0_wp,1.0_wp,N+2)
        q  = [( q0     , i=1,N )]
        A  = newSparse(N,N)
        allocate(T1(0:N+1))
        allocate(T2(0:N+1))
        allocate(T3(0:N+1))
        T1(0)   = Tl
        T1(N+1) = Tr
        T2(0)   = Tl
        T2(N+1) = Tr
        T3(0)   = Tl
        T3(N+1) = Tr
        dx = x(2)-x(1)
        i = 1
        Ae = k/dx**2
        Aw = k/dx**2
        Ap = Ae+Aw
        call A%set(i,i  , Ap)
        call A%set(i,i+1,-Ae)
        q(i) = q(i)+Aw*Tl
        do i=2,N-1
            Ae = k/dx**2
            Aw = k/dx**2
            Ap = Ae+Aw
            call A%set(i,i-1,-Aw)
            call A%set(i,i  , Ap)
            call A%set(i,i+1,-Ae)
        end do
        i = N
        Ae = k/dx**2
        Aw = k/dx**2
        Ap = Ae+Aw
        call A%set(i,i-1,-Aw)
        call A%set(i,i  , Ap)
        q(i) = q(i)+Ae*Tr
        T1(1:N) = biConjugateGradientStabilized(A,q)
        T2(1:N) = conjugateGradient(A,q)
        T3(1:N) = successiveOverRelaxation(A,q,1.995_wp)
        call figure()
        call subplot(1,1,1)
        call xylim(mixval(x),mixval(T1)+[0.0_wp,0.05_wp]*span(T1))
        call plot(x(::s),T1(::s),lineStyle='-',lineColor='r',markStyle='x',markColor='r')
        call plot(x(::s),T2(::s),lineStyle='-',lineColor='b',markStyle='o',markColor='b')
        call plot(x(::s),T3(::s),lineStyle='-',lineColor='c',markStyle='s',markColor='c')
        call ticks()
        call labels('Position #fix#fn','Temperature #fiT#fn','1D Heat Conduction with Generation')
    end subroutine testBasicSolvers
All Procedures
abs abs_t acos_t ad_t add_t arg arrayToChar asin_t assignment(=) atan_t bar barh biCGSTAB_t biConjugateGradientStabilized binData box charToArray checkPrecision colorbar colorbar2 colorize colorMap config_t conjg conjugateGradient conjugateGradient_t contour contourf cos_a cos_t cpuTime cubicSpline_t deDup DFT div_t doBar doContour doError doFillBetween doFunction doHist doLegend doLogPlot doPlot doQuiver doScatter doSurface endsWith errorbar eval_test eval_testN evalR_abs evalR_acos evalR_add evalR_asin evalR_atan evalR_cos evalR_div evalR_exp evalR_imag evalR_log evalR_log10 evalR_mul evalR_neg evalR_p evalR_pow evalR_real evalR_sin evalR_sqrt evalR_sub evalR_tan evalR_var evalZ_abs evalZ_acos evalZ_add evalZ_asin evalZ_atan evalZ_cos evalZ_div evalZ_exp evalZ_imag evalZ_log evalZ_log10 evalZ_mul evalZ_neg evalZ_p evalZ_pow evalZ_real evalZ_sin evalZ_sqrt evalZ_sub evalZ_tan evalZ_var exp exp exp_t f FFT FFT_freq figure fillBetween fillBetweenx findInterval flatten function_t gaussSeidel gaussSeidel_t hist iDFT iFFT imag_t intToChar inv jacobi jacobi_t labels legend linearInterp linearSpline_t lineSearch_t linspace log log log10 log10 log10_t log_t makeLogo matmul matmul maxval mean meshGridX meshGridY minimumResidual minval mixval mul_t neg_t newAbs newAcos newAdd newAsin newAtan newCos newDiv newExp newImag newIterator newLog newLog10 newMul newNeg newNodeStack newPow newReal newSin newSparse newSpvec newSqrt newSub newTan newToken newVar nint nodeStack_t norm2 norm2 operator(*) operator(*) operator(*) operator(**) operator(+) operator(+) operator(+) operator(-) operator(-) operator(.d.) operator(.o.) operator(.o.) operator(.oo.) operator(.sx.) operator(.x.) operator(/) operator(/) operator(<) operator(>) plot plot3 pop pow_t printTypes push quat_t quiver randomNormal randomUniform readGrid readStep real_t realToChar realToTime removeSpaces scaler scatter setRandomSeed setup show showProgress sin_a sin_t solveLU solveLU solverProgress SOR_t span sqrt sqrt_t startReport startsWith stDev steepestDescent sub_t subplot successiveOverRelaxation sum sum surface symmetricGaussSeidel symmetricSuccessiveOverRelaxation tan_a tan_t TDMA TDMA testBasic testBasicSolvers testColorize testColorMap testConstants testCpuTime testDeDup testDiff testDot testEndsWith testFFT testFlatten testFunction testIFFT testIntToChar testLinearInterp testLinspace testLU testMean testMeshGrid testMixval testNewConfig testNewSparse testNewSpline testNext testObjective testObjectiveN testPlot testPrecision testRandomNormal testRandomUniform testRead testReadGmsh testRealToChar testRealToTime testRemoveSpaces testSetRandomSeed testSolvers testSpan testSplineX testSpvec testStartsWith testStDev testTDMA testWallTime testWrite testWriteMat testWriteVTK testWriteVTK ticks title token_t tokenize toRPN transpose v2m var_t vector wait wallTime wireframe writeGrid writeGridVTK writeHeaderVTK writeMat writeScalarVTK writeStep writeVectorVTK xlabel xlim xticks xylim xyzlim ylabel ylim yticks
Call graph
testbasicsolvers calls conjugategradient, subplot, linspace, xylim, successiveoverrelaxation, biconjugategradientstabilized, newsparse, ticks, figure, span, mixval, labels, plot
conjugategradient calls startreport, solverprogress
subplot calls pladv, plvasp, plssub, plvpor, plvsta
xylim calls plwind
successiveoverrelaxation calls startreport, solverprogress
biconjugategradientstabilized calls startreport, solverprogress
newsparse calls newspvec
ticks calls plbox
figure calls pladv, plssub, plbop, pleop
labels calls pllab
plot calls plline, plptex, plssym
startreport calls showprogress
solverprogress calls showprogress
showprogress calls walltime, realtochar, colormap, realtotime, colorize
realtotime calls inttochar
colorize calls inttochar
testsparse_prg calls testbasicsolvers