ticks – CommonModules
ticks Subroutine
27 statements
Source File
public subroutine ticks(dx, dy, logx, logy, color, linewidth)
Set the ticks for the axes
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), optional :: dx
Spacing between ticks on x-axis
real(kind=wp), intent(in), optional :: dy
Spacing between ticks on y-axis
logical, intent(in), optional :: logx
Flag for log-ticks and labels on x-axis
logical, intent(in), optional :: logy
Flag for log-ticks and labels on y-axis
character(len=*), intent(in), optional :: color
Color code for ticks, box, and labels
real(kind=wp), optional :: linewidth
Line width for ticks and box
Calls
Called By
Source Code
ticks
Source Code
    subroutine ticks(dx,dy,logx,logy,color,lineWidth)
        !! Set the ticks for the axes
        real(wp),intent(in),optional::dx
            !! Spacing between ticks on x-axis
        real(wp),intent(in),optional::dy
            !! Spacing between ticks on y-axis
        logical,intent(in),optional::logx
            !! Flag for log-ticks and labels on x-axis
        logical,intent(in),optional::logy
            !! Flag for log-ticks and labels on y-axis
        character(*),intent(in),optional::color
            !! Color code for ticks, box, and labels
        real(wp),optional::linewidth
            !! Line width for ticks and box
        real(pp)::dxl,dyl
        character(10)::xopts,yopts
        dxl = 0.0_pp
        if(present(dx)) dxl = real(dx,pp)
        dyl = 0.0_pp
        if(present(dy)) dyl = real(dy,pp)
        xopts = 'bcnst'
        if(present(logx)) then
            if(logx) xopts = 'bcnstl'
        end if
        yopts = 'bcnstv'
        if(present(logy)) then
            if(logy) yopts = 'bcnstvl'
        end if
        call resetPen()
        if(present(color)) call setColor(color)
        if(present(lineWidth)) call setLineWidth(lineWidth)
        call plbox(xopts,dxl,0,yopts,dyl,0)
        call resetPen()
    end subroutine ticks
All Procedures
abs abs_t acos_t ad_t add_t arg arrayToChar asin_t assignment(=) atan_t bar barh biCGSTAB_t biConjugateGradientStabilized binData box charToArray checkPrecision colorbar colorbar2 colorize colorMap config_t conjg conjugateGradient conjugateGradient_t contour contourf cos_a cos_t cpuTime cubicSpline_t deDup DFT div_t doBar doContour doError doFillBetween doFunction doHist doLegend doLogPlot doPlot doQuiver doScatter doSurface endsWith errorbar eval_test eval_testN evalR_abs evalR_acos evalR_add evalR_asin evalR_atan evalR_cos evalR_div evalR_exp evalR_imag evalR_log evalR_log10 evalR_mul evalR_neg evalR_p evalR_pow evalR_real evalR_sin evalR_sqrt evalR_sub evalR_tan evalR_var evalZ_abs evalZ_acos evalZ_add evalZ_asin evalZ_atan evalZ_cos evalZ_div evalZ_exp evalZ_imag evalZ_log evalZ_log10 evalZ_mul evalZ_neg evalZ_p evalZ_pow evalZ_real evalZ_sin evalZ_sqrt evalZ_sub evalZ_tan evalZ_var exp exp exp_t f FFT FFT_freq figure fillBetween fillBetweenx findInterval flatten function_t gaussSeidel gaussSeidel_t hist iDFT iFFT imag_t intToChar inv jacobi jacobi_t labels legend linearInterp linearSpline_t lineSearch_t linspace log log log10 log10 log10_t log_t makeLogo matmul matmul maxval mean meshGridX meshGridY minimumResidual minval mixval mul_t neg_t newAbs newAcos newAdd newAsin newAtan newCos newDiv newExp newImag newIterator newLog newLog10 newMul newNeg newNodeStack newPow newReal newSin newSparse newSpvec newSqrt newSub newTan newToken newVar nint nodeStack_t norm2 norm2 operator(*) operator(*) operator(*) operator(**) operator(+) operator(+) operator(+) operator(-) operator(-) operator(.d.) operator(.o.) operator(.o.) operator(.oo.) operator(.sx.) operator(.x.) operator(/) operator(/) operator(<) operator(>) plot plot3 pop pow_t printTypes push quat_t quiver randomNormal randomUniform readGrid readStep real_t realToChar realToTime removeSpaces scaler scatter setRandomSeed setup show showProgress sin_a sin_t solveLU solveLU solverProgress SOR_t span sqrt sqrt_t startReport startsWith stDev steepestDescent sub_t subplot successiveOverRelaxation sum sum surface symmetricGaussSeidel symmetricSuccessiveOverRelaxation tan_a tan_t TDMA TDMA testBasic testBasicSolvers testColorize testColorMap testConstants testCpuTime testDeDup testDiff testDot testEndsWith testFFT testFlatten testFunction testIFFT testIntToChar testLinearInterp testLinspace testLU testMean testMeshGrid testMixval testNewConfig testNewSparse testNewSpline testNext testObjective testObjectiveN testPlot testPrecision testRandomNormal testRandomUniform testRead testReadGmsh testRealToChar testRealToTime testRemoveSpaces testSetRandomSeed testSolvers testSpan testSplineX testSpvec testStartsWith testStDev testTDMA testWallTime testWrite testWriteMat testWriteVTK testWriteVTK ticks title token_t tokenize toRPN transpose v2m var_t vector wait wallTime wireframe writeGrid writeGridVTK writeHeaderVTK writeMat writeScalarVTK writeStep writeVectorVTK xlabel xlim xticks xylim xyzlim ylabel ylim yticks
Call graph
ticks calls plbox
doerror calls ticks
dobar calls ticks
testbasicsolvers calls ticks
dologplot calls ticks
animate_prg calls ticks
docontour calls ticks
makelogo calls ticks
dohist calls ticks
basic_prg calls ticks
dofillbetween calls ticks
testsplinex calls ticks
testsolvers calls ticks
dolegend calls ticks
doquiver calls ticks
dofunction calls ticks
doscatter calls ticks
examples_prg calls doerror, dobar, dologplot, docontour, dohist, dofillbetween, dolegend, doquiver, doscatter
testsparse_prg calls testbasicsolvers, testsolvers
logo_prg calls makelogo
testspline_prg calls testsplinex
testfunction calls dofunction
testeval_prg calls testfunction