animate_prg – CommonModules
animate_prg Program
29 statements
Source File
Uses:
kinds_mod
array_mod
plplotlib_mod
Create a series of plots for an animation
Calls
Variables
x y t N M i k
Functions
f
Source Code
animate_prg
Variables
Type Attributes Name Initial
real(kind=wp), dimension(:), allocatable :: x
real(kind=wp), dimension(:), allocatable :: y
real(kind=wp), dimension(:), allocatable :: t
integer :: N
integer :: M
integer :: i
integer :: k
Functions
pure function f(x, t) result(o)
Function for plot
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: x
real(kind=wp), intent(in) :: t
Return Value real(kind=wp)
Source Code
program animate_prg
    !! Create a series of plots for an animation
    use kinds_mod
    use array_mod
    use plplotlib_mod
    implicit none
    real(wp),dimension(:),allocatable::x,y,t
    integer::N,M,i,k
    N = 100
    M = 1000
    x = linspace(0.0_wp,PI,N)
    t = linspace(0.0_wp,10.0_wp,M)
    call setup()
    do k=1,M
        y = [( f(x(i),t(k)) , i=1,N )]
        call figure()
        call subplot(1,1,1)
        call xylim(mixval(x),[-1.1_wp,1.1_wp])
        call plot(x,y,lineColor='b',lineWidth=2.0_wp)
        call ticks()
        call labels('x','y','')
    end do
    call show()
contains
    pure function f(x,t) result(o)
        !! Function for plot
        real(wp),intent(in)::x,t
        real(wp)::o
        o = sin(t)*cos(x+t)
    end function f
end program animate_prg
All Programs
animate_prg basic_prg examples_prg logo_prg testArray_prg testAutoDiff_prg testConfig_prg testEval_prg testFourier_prg testIterate_prg testKinds_prg testMatIO_prg testMesh_prg testNetCDF_prg testOptimize_prg testQuaternion_prg testSparse_prg testSpline_prg testStats_prg testTensor_prg testText_prg testTime_prg testVtkIO_prg
Call graph
animate_prg calls mixval, figure, setup, subplot, labels, show, plot, linspace, f, ticks, xylim
figure calls pleop, pladv, plbop, plssub
setup calls plsetopt, plinit, plsdev, plsfam, plsfnam, plfontld
subplot calls pladv, plssub, plvasp, plvsta, plvpor
labels calls pllab
show calls plend
plot calls plptex, plline, plssym
ticks calls plbox
xylim calls plwind