basic_prg – CommonModules
basic_prg Program
17 statements
Source File
Uses:
kinds_mod
array_mod
plplotlib_mod
Create a basic plot
Calls
Variables
x y
Source Code
basic_prg
Variables
Type Attributes Name Initial
real(kind=wp), dimension(:), allocatable :: x
real(kind=wp), dimension(:), allocatable :: y
Source Code
program basic_prg
    !! Create a basic plot
    !!
    !! ![plot](|media|/basic-1.svg)
    use kinds_mod
    use array_mod
    use plplotlib_mod
    implicit none
    real(wp),dimension(:),allocatable::x,y
    x = linspace(-2.0_wp,2.0_wp,101)
    y = x**2-1.0_wp
    call setup(device='svg',fileName='media/basic-%n.svg',figSize=[400,300])
    call figure()
    call subplot(1,1,1)
    call xylim(mixval(x),mixval(y))
    call plot(x,y,lineColor='r',lineWidth=2.0_wp)
    call ticks()
    call labels('#fix#fn','#fiy#fn','Plot')
    call show()
end program basic_prg
All Programs
animate_prg basic_prg examples_prg logo_prg testArray_prg testAutoDiff_prg testConfig_prg testEval_prg testFourier_prg testIterate_prg testKinds_prg testMatIO_prg testMesh_prg testNetCDF_prg testOptimize_prg testQuaternion_prg testSparse_prg testSpline_prg testStats_prg testTensor_prg testText_prg testTime_prg testVtkIO_prg
Call graph
basic_prg calls xylim, subplot, linspace, ticks, figure, setup, mixval, show, labels, plot
xylim calls plwind
subplot calls pladv, plvasp, plssub, plvpor, plvsta
ticks calls plbox
figure calls pladv, plssub, plbop, pleop
setup calls plsfnam, plsetopt, plsfam, plfontld, plinit, plsdev
show calls plend
labels calls pllab
plot calls plline, plptex, plssym