logo_prg – CommonModules
logo_prg Program
26 statements
Source File
Uses:
kinds_mod
array_mod
plplotlib_mod
Create the project logo
Calls
Subroutines
makeLogo
Source Code
logo_prg
Subroutines
subroutine makeLogo()
Create data and plot for logo
Arguments
None
Source Code
program logo_prg
    !! Create the project logo
    use kinds_mod
    use array_mod
    use plplotlib_mod
    implicit none
    call setup(device='pngqt',fileName='logo-%n.png',figSize=[128,128])
    call makeLogo
    call show()
contains
    subroutine makeLogo
        !! Create data and plot for logo
        real(wp),dimension(:),allocatable::x,y1,y2,y3
        x  = linspace(0.0_wp,1.0_wp,100)
        y1 = x**2-1.0_wp
        y2 = 2.0_wp*x-1.0_wp
        y3 = x
        y3 = cos(2.0_wp*PI*x)
        call figure()
        call subplot(1,1,1)
        call xylim(mixval(x),mixval([y1,y2,y3])*1.1_wp)
        call plot(x,y1,lineColor='b',lineWidth=10.0_wp)
        call plot(x,y2,lineColor='r',lineWidth=10.0_wp)
        call plot(x,y3,lineColor='c',lineWidth=10.0_wp)
        call ticks(lineWidth=5.0_wp)
        call labels('','','')
    end subroutine makeLogo
end program logo_prg
All Programs
animate_prg basic_prg examples_prg logo_prg testArray_prg testAutoDiff_prg testConfig_prg testEval_prg testFourier_prg testIterate_prg testKinds_prg testMatIO_prg testMesh_prg testNetCDF_prg testOptimize_prg testQuaternion_prg testSparse_prg testSpline_prg testStats_prg testTensor_prg testText_prg testTime_prg testVtkIO_prg
Call graph
logo_prg calls setup, makelogo, show
setup calls plsfnam, plsetopt, plsfam, plfontld, plinit, plsdev
makelogo calls xylim, subplot, linspace, ticks, figure, mixval, labels, plot
show calls plend
xylim calls plwind
subplot calls pladv, plvasp, plssub, plvpor, plvsta
ticks calls plbox
figure calls pladv, plssub, plbop, pleop
labels calls pllab
plot calls plline, plptex, plssym