testQuaternion_prg – CommonModules
testQuaternion_prg Program
15 statements
Source File
Uses:
kinds_mod
quaternion_mod
Test program for quaternion_mod
Todo
Add real tests
Calls
Subroutines
testBasic
Source Code
testQuaternion_prg
Subroutines
subroutine testBasic()
Arguments
None
Source Code
program testQuaternion_prg
    !! Test program for quaternion_mod
    !! @todo
    !! Add real tests
    use kinds_mod
    use quaternion_mod
    implicit none
    call testBasic
contains
    subroutine testBasic
        type(quat_t)::u,v,w
        u%s = 1.0_wp
        v%s = 2.0_wp
        w = u*v
        write(*,*) scaler(w),vector(w)
        write(*,*) w%getRotationMatrix()
    end subroutine testBasic
end program testQuaternion_prg
All Programs
animate_prg basic_prg examples_prg logo_prg testArray_prg testAutoDiff_prg testConfig_prg testEval_prg testFourier_prg testIterate_prg testKinds_prg testMatIO_prg testMesh_prg testNetCDF_prg testOptimize_prg testQuaternion_prg testSparse_prg testSpline_prg testStats_prg testTensor_prg testText_prg testTime_prg testVtkIO_prg
Call graph
testquaternion_prg calls testbasic
testbasic calls vector, scaler