testTime_prg – CommonModules
testTime_prg Program
22 statements
Source File
Uses:
kinds_mod
time_mod
Test program for time_mod
Calls
Subroutines
testCpuTime testWallTime
Source Code
testTime_prg
Subroutines
subroutine testCpuTime()
Test cpuTime to verify operation
Arguments
None
subroutine testWallTime()
Test wallTime to verify operation
Arguments
None
Source Code
program testTime_prg
    !! Test program for time_mod
    use kinds_mod
    use time_mod
    implicit none
    call testCpuTime
    call testWallTime
contains
    subroutine testCpuTime
        !! Test cpuTime to verify operation
        real(wp)::t0,t1
        t0 = cpuTime()
        call wait(0.1_wp)
        t1 = cpuTime()
        if( t1-t0>0.01_wp ) error stop "Failed cpuTime check"
    end subroutine testCpuTime
    subroutine testWallTime
        !! Test wallTime to verify operation
        real(wp)::t0,t1
        t0 = wallTime()
        call wait(0.1_wp)
        t1 = wallTime()
        if( t1-t0<0.1_wp ) error stop "Failed wallTime check"
    end subroutine testWallTime
end program testTime_prg
All Programs
animate_prg basic_prg examples_prg logo_prg testArray_prg testAutoDiff_prg testConfig_prg testEval_prg testFourier_prg testIterate_prg testKinds_prg testMatIO_prg testMesh_prg testNetCDF_prg testOptimize_prg testQuaternion_prg testSparse_prg testSpline_prg testStats_prg testTensor_prg testText_prg testTime_prg testVtkIO_prg
Call graph
testtime_prg calls testcputime, testwalltime
testcputime calls cputime
testwalltime calls walltime