testVtkIO_prg – CommonModules
testVtkIO_prg Program
29 statements
Source File
Uses:
kinds_mod
vtkIO_mod
array_mod
Test program for vtkIO_mod
Calls
Subroutines
testWriteVTK
Source Code
testVtkIO_prg
Subroutines
subroutine testWriteVTK()
Test writing VTK files
Arguments
None
Source Code
program testVtkIO_prg
    !! Test program for vtkIO_mod
    use kinds_mod
    use vtkIO_mod
    use array_mod
    implicit none
    call testWriteVTK
contains
    subroutine testWriteVTK
        !! Test writing VTK files
        real(wp),dimension(:),allocatable::x,y
        real(wp),dimension(:,:),allocatable::XX,YY
        real(wp),dimension(:,:),allocatable::F,U,V
        integer::N,M,iou
        N = 100
        M = 101
        x = linspace(0.0_wp,1.0_wp,N)
        y = linspace(0.0_wp,1.0_wp,M)
        XX = MeshGridX(x,y)
        YY = MeshGridY(x,y)
        F = XX*YY
        U = -YY
        V =  XX
        open(file='data.vtk',newunit=iou)
        call writeHeaderVTK(iou,'Test File')
        call writeGridVTK(iou,XX,YY)
        call writeScalarVTK(iou,'F',F)
        call writeVectorVTK(iou,'U',U,V)
        close(iou)
    end subroutine testWriteVTK
end program testVtkIO_prg
All Programs
animate_prg basic_prg examples_prg logo_prg testArray_prg testAutoDiff_prg testConfig_prg testEval_prg testFourier_prg testIterate_prg testKinds_prg testMatIO_prg testMesh_prg testNetCDF_prg testOptimize_prg testQuaternion_prg testSparse_prg testSpline_prg testStats_prg testTensor_prg testText_prg testTime_prg testVtkIO_prg
Call graph
testvtkio_prg calls testwritevtk
testwritevtk calls meshgridx, linspace, writescalarvtk, writegridvtk, writeheadervtk, meshgridy, writevectorvtk