testSpline_prg – CommonModules
testSpline_prg Program
57 statements
Source File
Uses:
kinds_mod
spline_mod
plplotlib_mod
array_mod
Test program for Spline_mod
Calls
Variables
x0 t0
Subroutines
testNewSpline testSplineX
Source Code
testSpline_prg
Variables
Type Attributes Name Initial
real(kind=wp), parameter, dimension(5,2) :: x0 = reshape([-2.0_wp, -1.0_wp, 0.0_wp, 1.0_wp, 2.0_wp, 3.0_wp, 0.0_wp, -1.0_wp, 0.0_wp, 3.0_wp], [5, 2])
real(kind=wp), parameter, dimension(5) :: t0 = [0.00_wp, 0.25_wp, 0.50_wp, 0.75_wp, 1.00_wp]
Subroutines
subroutine testNewSpline()
Arguments
None
subroutine testSplineX()
Arguments
None
Source Code
program testSpline_prg
    !! Test program for Spline_mod
    use kinds_mod
    use spline_mod
    use plplotlib_mod
    use array_mod
    implicit none
    real(wp),dimension(5,2),parameter::x0 = reshape( [ &
        & -2.0_wp,-1.0_wp, 0.0_wp,1.0_wp,2.0_wp , &
        &  3.0_wp, 0.0_wp,-1.0_wp,0.0_wp,3.0_wp &
        & ],[5,2])
    real(wp),dimension(5),parameter::t0 = &
        & [ 0.00_wp,0.25_wp,0.50_wp,0.75_wp,1.00_wp]
    call testNewSpline
    call testSplineX
contains
    subroutine testNewSpline
        type(cubicSpline_t)::spline
        spline = cubicSpline_t(t0,x0)
    end subroutine testNewSpline
    subroutine testSplineX
        type(cubicSpline_t)::sf,sc
        type(linearSpline_t)::sl
        real(wp),dimension(:,:),allocatable::xl,xf,xc,xt
        real(wp)::t
        integer::N,k
        N = 100
        sl = linearSpline_t(t0,x0)
        sf = cubicSpline_t(t0,x0,'finiteDifference')
        sc = cubicSpline_t(t0,x0,'conventional')
        allocate( xl(N,2) , xf(N,2) , xc(N,2) , xt(N,2) )
        do k=1,N
            t = real(k-1,wp)/real(N-1,wp)
            xl(k,1:2) = sl%x(t)
            xf(k,1:2) = sf%x(t)
            xc(k,1:2) = sc%x(t)
            xt(k,1:2) = [4.0_wp*t-2.0_wp,(4.0_wp*t-2.0_wp)**2-1.0_wp]
        end do
        call setup(fileName='spline-%n.svg',figSize=[400,300])
        call figure()
        call subplot(1,1,1)
        call xylim(mixval(xt(:,1)),mixval(xt(:,2)))
        call plot(xt(:,1),xt(:,2),lineStyle='-' ,lineColor='r',lineWidth=2.0_wp)
        call plot(xl(:,1),xl(:,2),lineStyle=':' ,lineColor='m',lineWidth=2.0_wp)
        call plot(xf(:,1),xf(:,2),lineStyle='-' ,lineColor='b',lineWidth=2.0_wp)
        call plot(xc(:,1),xc(:,2),lineStyle='--',lineColor='c',lineWidth=2.0_wp)
        call plot(x0(:,1),x0(:,2),lineStyle=''  ,markStyle='x',markColor='k')
        call ticks()
        call labels('x','y','Spline Test')
        call figure()
        call subplot(1,1,1)
        call xylim(mixval(xt(:,1)),[-2.0_wp,2.0_wp])
        call plot(xl(:,1),xl(:,2)-xt(:,2),lineStyle=':' ,lineColor='m',lineWidth=2.0_wp)
        call plot(xt(:,1),xt(:,2)-xt(:,2),lineStyle='-' ,lineColor='r',lineWidth=2.0_wp)
        call plot(xf(:,1),xf(:,2)-xt(:,2),lineStyle='-' ,lineColor='b',lineWidth=2.0_wp)
        call plot(xc(:,1),xc(:,2)-xt(:,2),lineStyle='--',lineColor='c',lineWidth=2.0_wp)
        call plot(x0(:,1),x0(:,2)-x0(:,2),lineStyle=''  ,markStyle='x',markColor='k')
        call ticks()
        call labels('x','y','Spline Test')
        call show()
    end subroutine testSplineX
end program testSpline_prg
All Programs
animate_prg basic_prg examples_prg logo_prg testArray_prg testAutoDiff_prg testConfig_prg testEval_prg testFourier_prg testIterate_prg testKinds_prg testMatIO_prg testMesh_prg testNetCDF_prg testOptimize_prg testQuaternion_prg testSparse_prg testSpline_prg testStats_prg testTensor_prg testText_prg testTime_prg testVtkIO_prg
Call graph
testspline_prg calls testnewspline, testsplinex
testnewspline calls cubicspline_t
testsplinex calls cubicspline_t, mixval, figure, setup, subplot, labels, show, plot, linearspline_t, ticks, xylim
figure calls pleop, pladv, plbop, plssub
setup calls plsetopt, plinit, plsdev, plsfam, plsfnam, plfontld
subplot calls pladv, plssub, plvasp, plvsta, plvpor
labels calls pllab
show calls plend
plot calls plptex, plline, plssym
ticks calls plbox
xylim calls plwind