testNetCDF_prg – CommonModules
testNetCDF_prg Program
33 statements
Source File
Uses:
kinds_mod
netCDF_mod
array_mod
Test program for netCFD_mod
Calls
Subroutines
testWrite testRead
Source Code
testNetCDF_prg
Subroutines
subroutine testWrite()
Test writing netCDF files
Arguments
None
subroutine testRead()
Test reading netCDF files
May fail due to write failure
Arguments
None
Source Code
program testNetCDF_prg
    !! Test program for netCFD_mod
    use kinds_mod
    use netCDF_mod
    use array_mod
    implicit none
    call testWrite
    call testRead
contains
    subroutine testWrite
        !! Test writing netCDF files
        real(wp),dimension(:),allocatable::x,y
        real(wp),dimension(:,:),allocatable::XX,YY,F
        x = linspace(0.0_wp,1.0_wp,100)
        y = linspace(0.0_wp,1.0_wp,101)
        XX = meshGridX(x,y)
        YY = meshGridY(x,y)
        F = XX*YY
        call writeGrid('data.nc',['F'],x,y)
        call writeStep('data.nc',0.0_wp,1,'F',F)
    end subroutine testWrite
    subroutine testRead
        !! Test reading netCDF files
        !! May fail due to write failure
        logical,dimension(1)::results
        real(wp),dimension(:),allocatable::x,y,z,t
        real(wp),dimension(:,:),allocatable::XX,YY,F
        character(3),dimension(:),allocatable::vars
        call readGrid('data.nc',vars,x,y,z,t)
        allocate(F(size(x),size(y)))
        call readStep('data.nc',trim(adjustl(vars(1))),F,1)
        XX = meshGridX(x,y)
        YY = meshGridY(x,y)
        results(1) = norm2(F-XX*YY)<1.0E-10_wp
        if( .not.any(results) ) error stop "Failed testRead[Write] check"
    end subroutine testRead
end program testNetCDF_prg
All Programs
animate_prg basic_prg examples_prg logo_prg testArray_prg testAutoDiff_prg testConfig_prg testEval_prg testFourier_prg testIterate_prg testKinds_prg testMatIO_prg testMesh_prg testNetCDF_prg testOptimize_prg testQuaternion_prg testSparse_prg testSpline_prg testStats_prg testTensor_prg testText_prg testTime_prg testVtkIO_prg
Call graph
testnetcdf_prg calls testwrite, testread
testwrite calls linspace, meshgridy, writegrid, writestep, meshgridx
testread calls meshgridy, meshgridx, readstep, readgrid
writegrid calls nf90_def_dim, nf90_enddef, nf90_create, nf90_def_var, nf90_close, nf90_put_var, nf90_put_att
readgrid calls nf90_close, nf90_open, nf90_inquire, nf90_inquire_dimension, nf90_get_var, nf90_inquire_variable