testIterate_prg – CommonModules
testIterate_prg Program
18 statements
Source File
Uses:
kinds_mod
iterate_mod
text_mod
time_mod
Test program for iterate_mod
Calls
Subroutines
testNext
Source Code
testIterate_prg
Subroutines
subroutine testNext()
Verify operation of next
Arguments
None
Source Code
program testIterate_prg
    !! Test program for iterate_mod
    use kinds_mod
    use iterate_mod
    use text_mod
    use time_mod
    implicit none
    call testNext
contains
    subroutine testNext
        !! Verify operation of next
        type(iterator_t)::iter
        iter = newIterator([5,5],[0.0_wp,0.0_wp],[1.0_wp,1.0_wp])
        do while(.not.iter%isDone)
            call showProgress('Testing',iter%getProgress())
            call wait(0.02_wp)
            call iter%next()
        end do
    end subroutine testNext
end program testIterate_prg
All Programs
animate_prg basic_prg examples_prg logo_prg testArray_prg testAutoDiff_prg testConfig_prg testEval_prg testFourier_prg testIterate_prg testKinds_prg testMatIO_prg testMesh_prg testNetCDF_prg testOptimize_prg testQuaternion_prg testSparse_prg testSpline_prg testStats_prg testTensor_prg testText_prg testTime_prg testVtkIO_prg
Call graph
testiterate_prg calls testnext
testnext calls showprogress, newiterator
showprogress calls walltime, realtochar, colormap, realtotime, colorize
realtotime calls inttochar
colorize calls inttochar